### PR TITLE
POSHI-28 Add new class to generate report on Macro Usage

### PR DESCRIPTION
**Pull request by CalumR23**
https://liferay.atlassian.net/browse/POSHI-28

### CODE REVIEW

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
Sent back with changes to Calum for testing
https://github.com/CalumR23/liferay-portal/pull/217

**Pull request closed without merging**
