### PR TITLE
POSHI-240

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/POSHI-240

@kenjiheigel

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional

**Comment by kenjiheigel** [comment]
@Tim-Cao, can you rework this? So you overrode the original dragAndDrop method by adding a new parameter into it. That would likely break existing functionality in master, and all the legacy branches as well. 

Can you create a new method called `dragAtAndDrop` and try to share some code between the two methods? For your new use case you can use the new method. Let me know if that doesn't make sense, thanks!

**Comment by Tim-Cao** [comment]
See https://github.com/kenjiheigel/liferay-portal/pull/953

**Pull request closed without merging**
