### PR TITLE
LRCI-4253 Fix attachments link for Playwright Trace and screenshots

### PR DESCRIPTION
**Pull request by CalumR23**
https://liferay.atlassian.net/browse/LRCI-4253

### CODE REVIEW

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by CalumR23** [comment]
ci:test:stable

**Comment by kenjiheigel** [comment]
ci:forward:force

**Comment by kenjiheigel** [comment]
ci:forward:force

**Pull request closed without merging**
