### PR TITLE
POSHI-108 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/POSHI-108

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
@Tim-Cao , made some minor changes and sent to Peter.
https://github.com/pyoo47/liferay-portal/pull/1494

**Pull request closed without merging**
