### PR TITLE
POSHI-253 Fix regex to catch more cases

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Issue:
SF failed on 7.3.x and 7.2.x

See: https://issues.liferay.com/browse/POSHI-253

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
Resent here: 
https://github.com/kenjiheigel/liferay-portal/pull/999

**Comment by ling-alan-huang** [comment]
https://github.com/kenjiheigel/liferay-portal/pull/1000

**Pull request closed without merging**
