### PR TITLE
LPS-93513

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@hhuijser, @ling-alan-huang, just heads up will send this in tomorrow EOD (PST). Talked to the Portal QA leads, and that was what they requested, to prevent rebase disruptions for their team.

**Comment by kenjiheigel** [comment]
@ling-alan-huang, I was about to send this in, but I found an issue unfortunately... There appears to be some data loss after running source format. Could you look into this when you get a chance. Thanks! 

https://github.com/kenjiheigel/liferay-portal/commit/114cdb849bc043b6292d4272a6ec5b05b832ce79#diff-5f077d986b57c499e17331731d7c81b6L144

**Comment by ling-alan-huang** [comment]
Closing, I will resend.

**Comment by ling-alan-huang** [comment]
ci:close

**Pull request closed without merging**
