### PR TITLE
POSHI-211 Fix poshi script parsing to generate Poshi files

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/POSHI-211

Previous pull: https://github.com/kenjiheigel/liferay-portal/pull/900

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by ling-alan-huang** [comment]
ci:test:relevant:nocompile

**Comment by kenjiheigel** [comment]
ci:forward

**Pull request closed without merging**
