### PR TITLE
LRCI-2329 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRCI-2329

This is only for master.

@kenjiheigel

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
Hi @kenjiheigel, the rest failure cases are related to dnd issues, the drop feedback is not shown when move a portlet to another layout column. I cannot reproduce on local. I don't have any idea about how to fix that.
Remember to cherry-pick https://github.com/kenjiheigel/liferay-portal/pull/826/commits/1d2577a2966193b5e8e1f715b17fd7b4d59b8432

**Comment by kenjiheigel** [comment]
Combined into https://github.com/kenjiheigel/liferay-portal/pull/815

**Pull request closed without merging**
