### PR TITLE
LRCI-4023 Modify rules based on batch types

### PR DESCRIPTION
**Pull request by brittneyq**
https://liferay.atlassian.net/browse/LRCI-4801

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:relevant

**Comment by brittneyq** [comment]
FYI @kenjiheigel , I had some SF issues in `modules/apps/asset/asset-list-test/src/testIntegration/java/com/liferay/asset/list/asset/entry/provider/test/AssetListAssetEntryProviderTest.java ` but I never modified it, I think it was introduced in upstream. I fixed it in the SF commit.

Also I disabled the playwright sf check because it would have errors such as 
```
1: Missing property "playwright.test.project[playwright-js-tomcat90-mysql57][relevant][asset-publisher-web-java-rule]": ./modules/apps/asset/asset-publisher-web/test.properties (SourceCheck:PropertiesPlaywrightTestCheck)
     [java] 2: Missing property "playwright.test.project[playwright-js-tomcat90-mysql57][relevant][blogs-web-functional-rule]": ./modules/apps/blogs/blogs-web/test.properties (SourceCheck:PropertiesPlaywrightTestCheck)
     [java] 3: Missing property "playwright.test.project[playwright-js-tomcat90-mysql57][relevant][depot-web-functional-rule]": ./modules/apps/depot/depot-web/test.properties (SourceCheck:PropertiesPlaywrightTestCheck)
     [java] 4: Missing property "playwright.test.project[playwright-js-tomcat90-mysql57][relevant][document-library-web-functional-rule]": ./modules/apps/document-library/document-library-web/test.properties (SourceCheck:PropertiesPlaywrightTestCheck)
     [java] 5: Missing property "playwright.test.project[playwright-js-tomcat90-mysql57][relevant][frontend-editor-ckeditor-web-functional-rule]": ./modules/apps/frontend-editor/frontend-editor-ckeditor-web/test.properties (SourceCheck:PropertiesPlaywrightTestCheck)
```
which is because we have multiple rules listed now but not all have a playwright batch. 

If my changes look good, I'll let Alan know there will probably need changes for the SF check.

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:forward

**Pull request closed without merging**
