### PR TITLE
LPS-172074 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LPS-172074

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:search:nocompile

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by kenjiheigel** [comment]
ci:forward

**Pull request closed without merging**
