### PR TITLE
LRCI-2329 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRCI-2329

This is only for master.

@kenjiheigel

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
Hi @kenjiheigel, Good news. All related issue are fixed. They are ready to go!

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
Will send in https://github.com/kenjiheigel/liferay-portal/pull/815

**Pull request closed without merging**
