### PR TITLE
POSHI-110 | Add new methods to BaseWebDriverImpl for ocular

### PR DESCRIPTION
**Pull request by lucasneves91**

### CODE REVIEW

**Comment by lucasneves91** [comment]
ci:test:sf

**Comment by lucasneves91** [comment]
ci:test:relevant

**Comment by lucasneves91** [comment]
@kenjiheigel

**Comment by kenjiheigel** [comment]
See my minor changes: 
https://github.com/kenjiheigel/liferay-portal/compare/e1f691ab495b94036aa2ad7548ab2c786b2534a2%5E...65cec19c630a46f11bdcd0cf0726f15ef0efe38f

Pushed to Peter.
https://github.com/pyoo47/liferay-portal/pull/1559

**Pull request closed without merging**
