### PR TITLE
POSHI-36 POSHI-421 Deprecate methods in resources and portal-web | POSHI-74 Consolidate poshi property for poshi files into a list

### PR DESCRIPTION
**Pull request by CalumR23**
https://issues.liferay.com/browse/POSHI-36
https://issues.liferay.com/browse/POSHI-74
https://issues.liferay.com/browse/POSHI-421

### CODE REVIEW

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
For SF, I think this change needs to be sorted: 
https://github.com/kenjiheigel/liferay-portal/pull/1186/commits/446a3314138f38b99f3c38a6023595e76f810069#diff-5dab8ecc42e1ccb7c5331a56ff5896d8584820997ac8e80425fab89d5e66d8f3

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
Resent here: 
https://github.com/kenjiheigel/liferay-portal/pull/1192

**Pull request closed without merging**
