### PR TITLE
LPS-65660 - Mobile save button is not visible in configuration iFrames

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-65660

I'm also sending one for ee7.0.x.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@pat270, there's a lot of test failures that are in CI right now. So I'm going to wait for those test issues to be resolved before I can check this pull. Hopefully by tomorrow.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
To summarize what was discussed with @pat270 yesterday. I believe there was a bug that was introduced in this pull. These were the steps identified to reproduce the issue. 
* Add a DDL List
* Add a DDL Display portlet to a page 
* Select the list

The list cannot be selected and the info message is not updated.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41564

**Comment by jbalsas** [comment]
Hey guys, this PR was for [LPS-65660](https://issues.liferay.com/browse/LPS-65660) and the linked one is for [LPS-65671](https://issues.liferay.com/browse/LPS-65671).

Could you please clarify this information and update the JIRA tickets properly?

Thanks!

**Comment by kenjiheigel** [comment]
@jbalsas, this one is still in progress, but I mislabeled it. I sent it back to @pat270, to investigate a potential bug that was introduced. Will keep you posted on the status though.

**Comment by kenjiheigel** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/41688
https://github.com/brianchandotcom/liferay-portal-ee/pull/13794

**Pull request closed without merging**
