### PR TITLE
Poshi 418 Poshi Release 1.0.381

### PR DESCRIPTION
**Pull request by CalumR23**
https://issues.liferay.com/browse/POSHI-418
Testing done here: https://github.com/kenjiheigel/liferay-portal/pull/1174

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by CalumR23** [comment]
ci:test:sf

**Pull request closed without merging**
