### PR TITLE
POSHI-190 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/POSHI-190

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@Tim-Cao , thanks for the pull. Next time, before you start work on Poshi tickets, could you please coordinate with us beforehand so we don't duplicate work? Calum has actually been looking into a solution. Calum and I will discuss the approach for this tomorrow and we'll let you know what we end up using.

**Comment by Tim-Cao** [comment]
@kenjiheigel, sure thing. I was on vacation last week and came back yesterday. I saw the ticket is at open status. I will double check next time

**Comment by CalumR23** [comment]
@Tim-Cao we decided to make a new Util class within Poshi and will be heading down that route. Thank you for your pull.

**Comment by Tim-Cao** [comment]
@CalumR23  Got it.

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
