### PR TITLE
LPS-106232 Upgrade CI testing to a version of Liferay Faces that is compatible with Liferay Portal 7.3	

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@kenjiheigel Please run the Liferay Faces (JSF) tests in CI with this pull request and let me know if we get better results. Thanks, Neil

**Comment by michaelhashimoto** [comment]
ci:test:jsf:nocompile

**Comment by ngriffin7a** [comment]
@kenjiheigel @michaelhashimoto the `github.upstream.branch.name` value for liferay-faces-portal should be changed from `3.x` to `4.x`

Please let me know if there is something I should change in the source tree. I searched the source code for "3.x" but can't find any occurrence that matches. Perhaps this is something within the CI system?

Thanks,

Neil

**Comment by michaelhashimoto** [comment]
@ngriffin7a - Sorry about that, I think kenji and I were both off on Monday.  I am retrying this pull with an updated reference.  If it looks okay, I'll commit the jenkins changes.  Thanks!

**Comment by michaelhashimoto** [comment]
@ngriffin7a - It seems to have gotten further with the CI update to point to <code>4.x</code>!  However, it still seemed to have failed with the following error:
<pre>     [exec] [ERROR] Failed to execute goal on project com.liferay.faces.demo.alloy.showcase.portlet: Could not resolve dependencies for project com.liferay.faces.demo:com.liferay.faces.demo.alloy.showcase.portlet:war:4.2.0-SNAPSHOT: Could not find artifact com.liferay.faces:com.liferay.faces.bridge.impl:jar:4.2.0-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
     [exec] [ERROR] 
     [exec] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
     [exec] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
     [exec] [ERROR] 
     [exec] [ERROR] For more information about the errors and possible solutions, please read the following articles:
     [exec] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
     [exec] [ERROR] 
     [exec] [ERROR] After correcting the problems, you can resume the build with the command
     [exec] [ERROR]   mvn <goals> -rf :com.liferay.faces.demo.alloy.showcase.portlet</pre>

I sent in the update to point the <code>master</code> liferay-portal branches to <code>4.x</code> instead of <code>3.x</code>.  Does this change need to happen for the <code>7.2.x</code> liferay-portal branches as well?

Please let me know.  Thanks!

**Comment by kenjiheigel** [comment]
ci:test:jsf

**Comment by kenjiheigel** [comment]
ci:test:jsf:nocompile

**Comment by ngriffin7a** [comment]
@kenjiheigel Please change the hash inside of git-commit/liferay-faces-bridge-impl to 31e19c170bbdce3e98e08a560a8c935392ebd69d

But then, in whatever build script runs `mvn clean install` in order to build the Liferay Faces artifacts from that commit, please add `-P liferay73` to the command line in order to make sure stuff gets built for testing against the liferay-portal master branch (currently 7.3). Thanks.

/cc @ctampoya

**Comment by kenjiheigel** [comment]
@ngriffin7a, got it. Testing here:
https://github.com/kenjiheigel/liferay-portal/pull/536

**Pull request closed without merging**
