### PR TITLE
LRCI-2329 Update to chromedriver 86

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-2329

Only for master. cc-ing: @Tim-Cao

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:acceptance-functional

**Comment by kenjiheigel** [comment]
ci:test:acceptance-functional:nocompile

**Comment by kenjiheigel** [comment]
ci:test:acceptance-functional:nocompile

**Comment by kenjiheigel** [comment]
ci:test:acceptance-functional:nocompile

**Comment by kenjiheigel** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
See https://github.com/kenjiheigel/liferay-portal/pull/827

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:reevaluate:1217401_8229

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by Tim-Cao** [comment]
Rebased then resent https://github.com/kenjiheigel/liferay-portal/pull/830

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
