### PR TITLE
POSHI-343 Poshi script changes for SF

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-340
https://issues.liferay.com/browse/POSHI-343

Please publish poshi-core and poshi-runner after merging. Thanks! 

cc-ing: @ling-alan-huang

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
@kenjiheigel `ci:test:sf` failed because SF is using old version of `poshi-core`.

**Comment by kenjiheigel** [comment]
ci:forward

**Pull request closed without merging**
