### PR TITLE
LPS-68581-test

### PR DESCRIPTION
**Pull request by kenjiheigel**
LPS-68581-test

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by zxdgoal** [comment]
@kenjiheigel 

Do we still face some problem with pr?

Thanks
John.

**Comment by kenjiheigel** [comment]
@zxdgoal, yeah still figuring out how to reproduce this locally. Going to try again this afternoon. Sorry for the delay!

**Comment by kenjiheigel** [comment]
Discovered the cause. The lpkg batch jobs were running on Firefox 38. 
https://issues.liferay.com/browse/LRQA-29428

I'll resend this pull once jenkins has been updated by QA Engineering.

**Pull request closed without merging**
