### PR TITLE
POSHI-423

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/POSHI-423

@kenjiheigel

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
@Tim-Cao, no need for this type of commit: 
https://github.com/kenjiheigel/liferay-portal/pull/1179/commits/2b08d616df1f8f7a836b4d990c15168951395c59

Thanks!

**Comment by kenjiheigel** [comment]
Resent here: https://github.com/kenjiheigel/liferay-portal/pull/1181

**Comment by kenjiheigel** [comment]
Sent to BChan: 
https://github.com/brianchandotcom/liferay-portal/pull/125226

**Pull request closed without merging**
