### PR TITLE
LRCI-2831 Use the macrodef

### PR DESCRIPTION
**Pull request by ling-alan-huang**
SF issue:
`1: Target 'prepare-selenium-login-config' does not exist: /home/alan/liferay_code/master/liferay-portal/build-test-tck.xml (SourceCheck:XMLBuildFileCheck)
`

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
@kenjiheigel can I make this changes?

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
Thanks for the catch and fix @ling-alan-huang !

**Pull request closed without merging**
