### PR TITLE
LPD-36494

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://liferay.atlassian.net/browse/LPD-36494
https://liferay.atlassian.net/browse/LRCI-4871

Re: https://github.com/brianchandotcom/liferay-portal/pull/155713#issuecomment-2448574268

I reworked the logic to find the workspace's portal-ext.properties if available for any client extension. This will happen for any client extension deployment: 
https://github.com/kenjiheigel/liferay-portal/pull/1768/commits/3700fe8f09c5f459c78e841977f5ce283d96cf59

cc: @thiago-buarqque

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:playwright

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:close

**Pull request closed without merging**
