### PR TITLE
POSHI-220

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/POSHI-220

@kenjiheigel

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @kenjiheigel, Poshi doesn't allow to assign an Int to variable when declare
```
     [exec]     Invalid Poshi Script syntax at:
     [exec]     > 37 |        var i = 0;
```

However, Poshi allow to assign an Int to variable in this way.

`var i = ${i} + 1;`

That's the reason I change the return type of ListUtil.get and ListUtil.size to String

Output is
```
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.PortalSmoke#ListDemo] STANDARD_OUT
     [exec]     ## A 9 ##
     [exec]     ## B 8 ##
     [exec]     ## C 7 ##
     [exec]     ## D 6 ##
     [exec]     ## E 5 ##
```

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
I asked Calum to add additional changes here https://github.com/kenjiheigel/liferay-portal/pull/929

**Pull request closed without merging**
