### PR TITLE
LRCI-4526 Don't compare PR's stable result to upstream

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://liferay.atlassian.net/browse/LRCI-4526

cc: @pyoo47

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
@kenjiheigel Are you sure this won't prevent the relevant results from being compared to upstream?

**Comment by kenjiheigel** [comment]
I don't think it will because the stable evaluation is a separate area of logic, but I'm still doing testing.

**Pull request closed without merging**
