### PR TITLE
LRCI-3881 Add playwright testing support to CI

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://liferay.atlassian.net/browse/LRCI-3881

Tested here: 
https://github.com/kenjiheigel/liferay-portal/pull/1486

cc: @pyoo47, @marco-leo

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:stable:nocompile

**Comment by kenjiheigel** [comment]
ci:test:playwright:nocompile

**Comment by kenjiheigel** [comment]
The `playwright` suite failed due to some properties not being propagated in mirrors. It will get pushed up later tonight, so I'll rerun it again over the weekend.

**Comment by pyoo47** [comment]
ci:test:stable

**Comment by pyoo47** [comment]
ci:test:playwright:nocompile

**Comment by pyoo47** [comment]
ci:test:playwright

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:stable:nocompile

**Comment by kenjiheigel** [comment]
ci:test:playwright:nocompile

**Comment by kenjiheigel** [comment]
ci:forward:force

**Comment by kenjiheigel** [comment]
ci:forward:force

**Pull request closed without merging**
