### PR TITLE
Poshi-103

### PR DESCRIPTION
**Pull request by dellawang**
https://issues.liferay.com/browse/POSHI-103

@gaborlovasdotcom

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by dellawang** [comment]
ci:test:relevant:nocompile

**Comment by kenjiheigel** [comment]
Pushed to Peter.
https://github.com/pyoo47/liferay-portal/pull/1474/

@dellawang, just made some minor changes and applied SF: 
https://github.com/kenjiheigel/liferay-portal/compare/f9249938f5680dc732806d45b214ab4ef38fbba7%5E...8da3261d26bdd85feebca1c33a1f669b12e5e0e8

**Comment by dellawang** [comment]
> just made some minor changes and applied SF:

Thank you so much!

**Pull request closed without merging**
