### PR TITLE
POSHI-216

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/POSHI-216

@kenjiheigel

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
@Tim-Cao, sorry for the delayed reply. I'm not sure what this solves. This doesn't seem to change anything though. Let's talk about this more later.

**Comment by Tim-Cao** [comment]
See https://github.com/kenjiheigel/liferay-portal/pull/961

**Pull request closed without merging**
