### PR TITLE
LRCI-4237 Record job property and set test selector

### PR DESCRIPTION
**Pull request by brittneyq**
https://liferay.atlassian.net/browse/LRCI-4237

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
Resent here: 
https://github.com/kenjiheigel/liferay-portal/pull/1648

**Pull request closed without merging**
