### PR TITLE
POSHI-110 | Add new methods to LiferaySelenium for ocular

### PR DESCRIPTION
**Pull request by lucasneves91**
[POSHI-110](https://issues.liferay.com/browse/POSHI-110) - As a Tester writer, I should be able to use Ocular to compare images;

Sending LiferaySelenium changes in poshi-core first.

### CODE REVIEW

**Comment by lucasneves91** [comment]
ci:test:sf

**Comment by lucasneves91** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
Sent to Peter.
https://github.com/pyoo47/liferay-portal/pull/1549

**Comment by kenjiheigel** [comment]
ci:reevaluate:1021312_7426

**Comment by kenjiheigel** [comment]
ci:reevaluate:10213

**Comment by kenjiheigel** [comment]
ci:reevaluate:1021312_7426

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Pull request closed without merging**
