### PR TITLE
LPS-66534 Fix effects tests

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Kenji, I fixed some of the tests... not sure why I wrote them like that in the first place or how they even worked 😂 

Maybe something changed later in the module that invalidated those tests. 

They should be passing now, but I might change them later again once we have this in.

Thanks a lot!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
no tests for you! 😱

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/43498

**Pull request closed without merging**
