### PR TITLE
POSHI-211_PoshiParser_20211111_1

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Kenji,

I didn't touch these three files, they have the some issues that I have already reported to you today on Slack.

1.https://github.com/liferay/liferay-portal/blob/de822b41604cd5a0b940e75951b5e2fb1f002554/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/portalconfiguration/serveradministration/GroovyScript.testcase#L43

2.https://github.com/liferay/liferay-portal/blob/de822b41604cd5a0b940e75951b5e2fb1f002554/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/fragment/FragmentsEditor.testcase#L220

3.https://github.com/liferay/liferay-portal/blob/de822b41604cd5a0b940e75951b5e2fb1f002554/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/fragment/FragmentsWithStaging.testcase#L160

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
@kenjiheigel Did my changes break ci?

**Comment by kenjiheigel** [comment]
@ling-alan-huang it might have... We do some poshi parsing during CI, to pull meta data for test running. The errors for that relevant run are a bit odd. We might want to commit all the poshi-core changes first, then commit poshi changes separately. 

Does poshi need to be a dependency of SF now? or rather, how were the new poshi files generated?

**Comment by kenjiheigel** [comment]
Basically, for poshi, we use a released jar version, not source poshi to parse everything. to prevent regressions. So it might be due to a mismatch between new files generated based off your changes, and the old jar. Ideally, whatever SF is doing with poshi, should match the version of poshi that is being used across the projects.

**Comment by ling-alan-huang** [comment]
@kenjiheigel SF does use `poshi-core` module at present, if the changes are merged, SF will add `poshi-core` dependencies in `modules/util/source-formatter/build.gradle`, and regenerate poshi files.

I added some logic on my logcal to generated poshi files.
like:
```
	PoshiElement actualElement = _getPoshiElement(fileName);

	String actualPoshiSyntax = Dom4JUtil.format(actualElement);

private PoshiElement _getPoshiElement(String absolutePath)
	throws Exception {
		return (PoshiElement)PoshiNodeFactory.newPoshiNodeFromFile(
		FileUtil.getURL(_getFile(absolutePath)));
}

private File _getFile(String absolutePath) {
	return new File(absolutePath);
}


```

**Comment by kenjiheigel** [comment]
Resent here for forwarding
https://github.com/kenjiheigel/liferay-portal/pull/900

I fixed the issue regarding the 3 files you mentioned, fixed the unit tests, and fixed validation as well. 

Additionally, I'm only going to send up the poshi-core changes first. We can regenerate the files at a later point, after a poshi release.

**Pull request closed without merging**
