### PR TITLE
POHSI-211

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Kenji, 

See: https://liferay.slack.com/archives/CR6GDGESY/p1638428803050000

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
Related pulls:
7.3.x: https://github.com/kenjiheigel/liferay-portal-ee/pull/284
7.2.x: https://github.com/kenjiheigel/liferay-portal-ee/pull/285
7.1.x: https://github.com/kenjiheigel/liferay-portal-ee/pull/286
7.0.x: https://github.com/kenjiheigel/liferay-portal-ee/pull/287

**Comment by ling-alan-huang** [comment]
@kenjiheigel Do we need to use "\"" in `StringUtil.regexReplaceAll`? I not sure how the parameter("${xxx}") goes in there.

**Comment by kenjiheigel** [comment]
Yeah, we'd need to b/c it's basically passing in a regular expression as the string. I feel like it'd be better if people use the multiline var though, and pass it in, instead of using the string directly.

**Comment by ling-alan-huang** [comment]
Anyway just let me know if you need me to make any changes.

**Pull request closed without merging**
