### PR TITLE
POSHI-216 POSHI-243 DateUtil updates

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-216
https://issues.liferay.com/browse/POSHI-243

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@Tim-Cao, thanks for your efforts in these updates. I was going to send back for you to make some changes, but I know you're on vacation, so I made the changes myself. 

For what you did for POSHI-216, I see why that functionality is necessary, but your implementation will break some existing usages, particularly by adding another parameter to [`getFormattedDate`](https://github.com/kenjiheigel/liferay-portal/pull/963/commits/5c6754315ece12175922036dd9615d7c2708ea48#diff-575bad888abc49801d3c5d080f3eacd9ab617f6e1d611cc543363e335c6e0b77R63-R64). No validation errors will be thrown, but there will definitely be runtime issues in certain tests. 

Additionally, the way DateUtil has been previously implemented makes it a bit inflexible, in that the only possible offsets are days, which is inherently problematic. 

For POSHI-243, that also works, but it turns out to be only a one time solution. I ended up adding a timezone parameter, and while it doesn't give a method that gives the exact output of the user, it can give the output with the correct timezone and date format pattern. 

The main goal of util changes that we have are to: 
1. Not break existing functionality 
2. Not solve specific issues, but provide clear and flexible methods that will allow them to solve the issue themselves.

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Thanks for your fix. @kenjiheigel I will keep them in mind.

**Pull request closed without merging**
