### PR TITLE
POSHI-46 & POSHI-79

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/POSHI-46
https://issues.liferay.com/browse/POSHI-79

### CODE REVIEW

**Comment by pyoo47** [comment]
@kenjiheigel I made a few changes to your pull request. Could you retest it and forward it to BChan if I didn't break anything?

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:forward

**Pull request closed without merging**
