### PR TITLE
LPS-110747

### PR DESCRIPTION
**Pull request by kenjiheigel**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sharepoint

**Comment by kenjiheigel** [comment]
@adolfopa, I think I may have found the issue. I printed out the responses from the curls: 
```
     [exec]     {"hostname":"cloud-10-0-15-1","stolen":false}
```
Your regex (`\"hostname\" *: *\"([^\"]+)\"`) doesn't match to the whole string when you use `matcher.matches()`. Going to try a `matcher.find()` and we'll see if that works.

**Comment by kenjiheigel** [comment]
@adolfopa, @austinchiang looks like that worked! 

One thing I think you could improve with this though, is could you use one Sharepoint VM for all those tests? Each unit test eats up one sharepoint VM, and will lock it for 20 minutes. Could you potentially use JUnit's `@BeforeClass` to get the sharepoint VM and reuse the same one? If it doesn't work, then at least lower the "lease time" to 5 minutes possibly? The tests run super quick. 

Also, could you add logic to clean and release the sharepoint VMs in the teardown too? (https://liferay.slack.com/archives/CL3TWSMHQ/p1585156675023600?thread_ts=1585127058.014500&cid=CL3TWSMHQ) 

Maybe you have the logic in there somewhere, but I didn't see it though.

**Comment by adolfopa** [comment]
Thanks a log @kenjiheigel !

I'll look into those asap.

**Comment by adolfopa** [comment]
See https://github.com/kenjiheigel/liferay-portal/pull/584

**Pull request closed without merging**
