### PR TITLE
Lpd 36494 final

### PR DESCRIPTION
**Pull request by thiago-buarqque**

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:playwright

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
Aborted the jobs and retesting here after fixing SF: 
https://github.com/kenjiheigel/liferay-portal/pull/1768

**Pull request closed without merging**
