### PR TITLE
POSHI-228

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/POSHI-228

@kenjiheigel

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional

**Comment by kenjiheigel** [comment]
Resent:
https://github.com/Tim-Cao/liferay-portal/pull/674

**Pull request closed without merging**
