### PR TITLE
POSHI-65 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/POSHI-65

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
@Tim-Cao , @victorg1991 , I tested using this: 
```
function getElementByXpath(path) {
  return document.evaluate(path, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
}

var cmElement = getElementByXpath("//div[contains(@class,'CodeMirror cm-s-default')]");

cmElement.CodeMirror.setValue("<test></test>");
```

Reference:
https://stackoverflow.com/a/29452391/4484203

Looks like we're using [CodeMirror 5.52](https://github.com/liferay/liferay-portal/blob/master/modules/apps/fragment/fragment-web/package.json#L5)

Is this change ok?

**Comment by kenjiheigel** [comment]
I applied this additional change here: 
https://github.com/kenjiheigel/liferay-portal/pull/585

**Comment by victorg1991** [comment]
Hey @kenjiheigel that change is ok, I've just tried it and work perfectly
Thanks :)

**Pull request closed without merging**
