### PR TITLE
LRQA-12004 UI Taglibs Sample Portlet - Fixed formatting

### PR DESCRIPTION
**Pull request by thektan**
Hey @kenjiheigel!

I fixed the formatting issues. Most of them weren't meant to be language keys, but I changed them anyway so it wouldn't throw any errors. Let me know if there are any other issues that come up!

Thanks!

### CODE REVIEW

**Comment by thektan** [comment]
Hmmm that's weird. My source formatter didn't throw any errors. I'll look into this though.

**Comment by thektan** [comment]
I fixed the current error being thrown by the source formatter. I had to wrap the boolean values as `<%= true %>` rather than just `true`.

I'm still looking into the other error being thrown by the `generateJSPJava` task, but hopefully no more source formatting issues.

**Comment by kenjiheigel** [comment]
@thektan, thanks! was just looking into that.

**Comment by thektan** [comment]
Looks like the build was failing because of the catch exception blocks, so I just removed them. I don't think they're necessary anymore anyway.

**Comment by thektan** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by thektan** [comment]
Rebased against master and fixed the issue by editing `LRQA-12004 Exclude module from portal build` (7427e6f) to add the exclude to `build.properties` since the excludes were recently moved there from these commits: 15a2a4130570cf8cec419d598d53520a11378ae8...8340380a03c1fa6ed80fbacd2aa97c7d0dfc00d1

**Comment by thektan** [comment]
ci:retest

**Comment by thektan** [comment]
I'm going to try converting the files that are included in the view from `.jsp` to `.jspf` and retest this.

**Comment by thektan** [comment]
ci:retest

**Comment by thektan** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
There were some general issues when this last run, I don't think it was related to the actual branch though. Going to run the PR tester one more time.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by thektan** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by thektan** [comment]
Looks like one of the taglibs changed causing the generateJSPJava failure.

https://github.com/liferay/liferay-portal/commit/f31638b44dc11cef8cd75c54cd7ee6d9546eafaa

Updating and then I'll retest.

**Comment by thektan** [comment]
ci:retest

**Comment by thektan** [comment]
Looks like some of the java package paths got changed too, haha.

Updating and retesting.

**Comment by thektan** [comment]
ci:retest

**Comment by thektan** [comment]
Resent: https://github.com/kenjiheigel/liferay-portal/pull/85

**Pull request closed without merging**
