### PR TITLE
POSHI-119 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/POSHI-119

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:poshi

**Comment by kenjiheigel** [comment]
Pushed to Peter.
https://github.com/pyoo47/liferay-portal/pull/1535

@Tim-Cao, I took out the caching stuff. We'll just bump the version once a new poshi-core version is released after your changes get merged. 

Additionally see my minor changes: 
https://github.com/pyoo47/liferay-portal/pull/1535/commits/84ec0e559f09b3794d6f39fd6565896c297c16e1

Kind of a weird case we have to work around cause Poshi only uses strings, but in this case, length usually is already an int.

**Pull request closed without merging**
