### PR TITLE
LRCI-4063 Fix report cron

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://liferay.atlassian.net/browse/LRCI-4063

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
ci:help

**Comment by pyoo47** [comment]
ci:help

**Comment by kenjiheigel** [comment]
ci:forward

**Pull request closed without merging**
