### PR TITLE
LRCI-2150 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRCI-2150

This is only for master.

@kenjiheigel

As I know, there are two tags for plus icon
anchor: redirect to view page
button: toggle-dropdown
My solution is waitForPageLoad first
Then simple and modify the Button#PLUS locator to find the anchor or button
See https://github.com/kenjiheigel/liferay-portal/pull/778/commits/e2184b67e892ed9cf965cd91189b66df0f65bfcd

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:default:nocompile

**Comment by Tim-Cao** [comment]
The solution also doesn't work on the plus icon in Forms admin
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1524445454

**Comment by kenjiheigel** [comment]
@Tim-Cao thanks for trying, yeah, that's the issue I was running into as well.

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1524950706
The plus icon issue from Forms is resolved.

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
It adapts to the following situations:
Sites admin
Web Content admin
Forms admin
Blogs admin
Widget Templates popup
Teams admin
Specifications admin
Asset Libraries admin
Page Templates admin

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1525508178
It doesn't work on Forms admin if the locator doesn't have link part.

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
Hi @kenjiheigel，it seems like only one case failed by changes.

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
Not stable enough.

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
See https://github.com/kenjiheigel/liferay-portal/pull/785

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
