### PR TITLE
LPS-141109

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@hhuijser @ling-alan-huang , I'm working on fixing a dependent issue that needs to go in before we can apply this: https://issues.liferay.com/browse/POSHI-202

Once we fix that, I'll do a poshi release and we should be able to make these changes seamlessly without poshi validation issues, and I can forward this pull with poshi SF generated changes

**Comment by kenjiheigel** [comment]
Sent up poshi-core changes here: 
https://github.com/kenjiheigel/liferay-portal/pull/913

**Comment by kenjiheigel** [comment]
Retesting here: 
https://github.com/kenjiheigel/liferay-portal/pull/919
https://github.com/kenjiheigel/liferay-portal/pull/920

@hhuijser, @ling-alan-huang we're blocked on some stuff on the Jenkins side, as well as some changes that need to be made in the usage of poshi in SF as well. I let Alan know the issue. Won't be able to work on this further until next week.

**Comment by ling-alan-huang** [comment]
Kenji, 
I enabled SF on Poshi back since we are blocked here.
https://github.com/ling-alan-huang/liferay-portal/pull/561

**Comment by ling-alan-huang** [comment]
@kenjiheigel I sent the changes here: https://github.com/kenjiheigel/liferay-portal/pull/922

**Pull request closed without merging**
