### PR TITLE
LPS-68713 Do not try to resubmit or reload the page when SPA navigation fails, but show a notification instead.

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by jpince** [comment]
@brunobasto I think Kenji is out of the office today. Is there something specific you need him to look at? Or can this just go straight to BChan?

**Comment by brunobasto** [comment]
Hey @jpince,

Thanks for letting me know. This is a follow up on a conversation I had with. It's not urgent, so It's ok to wait until he is back.

Thanks,

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/43980

**Pull request closed without merging**
