### PR TITLE
POSHI-165 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/POSHI-165

This is only for master.

@kenjiheigel

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
@Tim-Cao, going to address this in another ticket, using a different implementation: 
https://issues.liferay.com/browse/POSHI-172

**Comment by Tim-Cao** [comment]
Thanks @kenjiheigel

**Pull request closed without merging**
