### PR TITLE
LRQA-35480 Implement take-screenshot, fail, task, toggle, on, off, elseif elements for readable Poshi

### PR DESCRIPTION
**Pull request by kevin-yen**
https://issues.liferay.com/browse/LRQA-35480

### CODE REVIEW

**Comment by kevin-yen** [comment]
ci:stop

**Comment by kevin-yen** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by kenjiheigel** [comment]
Pushed to Peter.
https://github.com/pyoo47/liferay-portal/pull/466

**Pull request closed without merging**
