### PR TITLE
LRQA-55018 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-55018

### CODE REVIEW

**Comment by john-co** [comment]
Hi @kenjiheigel,
Please review new poshi methods for copy and paste. Thank you!

**Comment by john-co** [comment]
reached out to @kenjiheigel to follow up, he'll review soon.

**Comment by kenjiheigel** [comment]
@john-co , @zhangyan0701 , sorry for the lag. 

I think it'd be best to rework this to work in other use cases. 

So essentially, what we're doing isn't specific to just the selectField, but rather, it's a copy command using Sikuli, which uses Robot. It will be more useful to rework this to account for other use cases if necessary. I think we can make a couple methods like `robotTypeShortcut` and `robotType` for those difficult use cases where you need to use the actual keyboard. How does this sound?

**Comment by john-co** [comment]
Thanks @kenjiheigel, sounds good with me.

**Comment by kenjiheigel** [comment]
Sent back to @john-co for testing: 
https://github.com/john-co/liferay-portal/pull/269

**Pull request closed without merging**
