### PR TITLE
POSHI-69 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/POSHI-69

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
@Tim-Cao , I'm off tomorrow, so won't get to look at this til some time next week. I don't quite understand what this is for. 

Also, do you think you guys are going to be sending these javascript changes more often now? I feel like we should maybe work out a better way to do this without having to add a javascript method every time something changes. Will think about this a bit more.

**Comment by Tim-Cao** [comment]
> @Tim-Cao , I'm off tomorrow, so won't get to look at this til some time next week. I don't quite understand what this is for. Could you give more context?
> 
> Also, do you think you guys are going to be sending these javascript changes more often now? I feel like we should maybe work out a better way to do this without having to add a javascript method every time something changes. Will think about this a bit more.

>@kenjiheigel Sure! This story would like to see restriction visual feedback when drag a Section element over anther Section or Column of Row. https://issues.liferay.com/browse/LPS-109717
The current javaScriptDragAndDrop can not meet this request so I open this request to add a new one.

**Comment by kenjiheigel** [comment]
@Tim-Cao , sorry for the delay on this. Could we try an alternative solution? I added some new methods with this in mind in [POSHI-75](https://issues.liferay.com/browse/POSHI-75). Basically, I think it will be better if you guys are able to contain javascript changes on the Poshi side, rather than having to add a new selenium method. This will give you more flexibility in the long run. Let me know how this works. 

Try creating a function file with this logic: 
```
@default = "dragOver"
definition {

	function dragOver {
		WaitForSPARefresh();

		var javaScript = '''
Simulate = {
	dragOver: async function(source, target) {
		const dataTransfer = new DataTransfer();

		const dispatchEvent = async(type, element) => {
			const rect = element.getBoundingClientRect();

			const event = new DragEvent(
				type,
				{
					bubbles: true,
					clientX: rect.left + (rect.width / 2),
					clientY: rect.top + (rect.height / 2),
					dataTransfer: dataTransfer,
					relatedTarget: element
				});

			element.dispatchEvent(event);
		};

		await dispatchEvent('dragstart', source);

		await dispatchEvent('dragover', target);

		await dispatchEvent('dragover', target);
	}
};

function getElementByXpath(path) {
	return document.evaluate(path, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
}

Simulate.dragOver(getElementByXpath(arguments[0]), getElementByXpath(arguments[1]));

		''';

		selenium.executeJavaScript("${javaScript}", "${locator1}", "${locator2}");

		selenium.assertJavaScriptErrors();

		selenium.assertLiferayErrors();
	}
}
```

Usage: `DragOver(locator1 = "//draggable", locator2 = "//droppable");`

**Comment by Tim-Cao** [comment]
@kenjiheigel Thanks for you help!

**Pull request closed without merging**
