### PR TITLE
LPS-68751 Fixes navigation error when navigating to the same screen. 'destroyPortlet' event should fire before the next screen is added to the page.

### PR DESCRIPTION
**Pull request by brunobasto**
Hey @kenjiheigel,

I'm sending this one to you because I fixed an issue with SPA when some navigation redirects to the same page the user was already at. This change should not break any tests, but I'm sending this one to you just so that we make sure.

Thanks,

### CODE REVIEW

**Comment by marcellustavares** [comment]
@brunobasto, tests failures

**Comment by marcellustavares** [comment]
ci:close

**Comment by brunobasto** [comment]
@marcellustavares I think those are expected from the changes introduced, right? We need test fixes for Forms.

**Comment by marcellustavares** [comment]
yeah, It seems to be related to the label changes.

**Comment by kenjiheigel** [comment]
Retesting with test fixes here:
https://github.com/kenjiheigel/liferay-portal/pull/312

**Comment by kenjiheigel** [comment]
@brunobasto, @marcellustavares, I can take care of this one. I'll let you guys know if you need to do anything else. 

fyi @vicnate5

**Comment by vicnate5** [comment]
Thanks @kenjiheigel

**Comment by kenjiheigel** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/44664

**Comment by fernandosouza** [comment]
In order to try to document, here is the comment that explains the needs of the fix: https://github.com/brunobasto/liferay-portal/pull/779#issuecomment-256968224

**Pull request closed without merging**
