### PR TITLE
POSHI-88 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/POSHI-88

This is only for master.

@kenjiheigel

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @kenjiheigel , I think the failures are caused by poshi not released.

**Comment by kenjiheigel** [comment]
@Tim-Cao , can you just send me the java changes by itself? We can't send them all together, that's why the tests failed. The other changes will have to be made once we do a Poshi release.

**Comment by kenjiheigel** [comment]
Java changes tested here: 
https://github.com/kenjiheigel/liferay-portal/pull/642

**Pull request closed without merging**
