### PR TITLE
LRCI-3759 Set timeout.explicit.wait to 60 seconds

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://liferay.atlassian.net/browse/LRCI-3759

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
Compared with EE Development Acceptance master https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2427930024&testrayRunIdA=2427753947&statusB=3

**Comment by Tim-Cao** [comment]
@kenjiheigel Failures are unrelated to this change.

**Comment by kenjiheigel** [comment]
ci:test:sf

**Pull request closed without merging**
