### PR TITLE
LPD-27195 LRCI-3880 LRCI-4274 Enable faro tests, fix js-unit test performance and grouping in CI

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://liferay.atlassian.net/browse/LPD-27195
https://liferay.atlassian.net/browse/LRCI-3880
https://liferay.atlassian.net/browse/LRCI-4274

cc: @interaminense, @pyoo47

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
Here is the PR with commits regarding the faro frontend SF and unit test failing on master https://github.com/liferay-ac/liferay-portal/pull/1653

**Comment by interaminense** [comment]
Resent https://github.com/liferay-ac/liferay-portal/pull/1653

**Comment by interaminense** [comment]
ci:close

**Pull request closed without merging**
