### PR TITLE
LPD-27195 LRCI-3880 LRCI-4274 Enable faro tests to frontend js-unit tests

### PR DESCRIPTION
**Pull request by kenjiheigel**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
@interaminense, the JS unit tests will still fail, but I found that our CI logic wasn't able to actually split up the tests. So even though it looks like they got split into 6 batches, each batch actually runs ALL the tests.  I'll be working to update the logic today.

**Comment by interaminense** [comment]
Got it @kenjiheigel, thank you!

**Comment by kenjiheigel** [comment]
Closing as testing is completed. Will resend another PR for forwarding.

**Pull request closed without merging**
