### PR TITLE
LRCI-3372

### PR DESCRIPTION
**Pull request by kenjiheigel**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:saml:nocompile

**Comment by kenjiheigel** [comment]
ci:test:saml:nocompile

**Comment by kenjiheigel** [comment]
ci:test:saml:nocompile

**Comment by gaborlovasdotcom** [comment]
Hi @kenjiheigel , I checked and the failed tests are executed twice:
### LocalFile.SAML#AssertSSOFailsWhenAlgorithmsMismatch
### LocalFile.SAML#AssertSignedSAMLMetadata

According to their Jenkins log.

**Comment by kenjiheigel** [comment]
ci:test:saml:nocompile

**Comment by kenjiheigel** [comment]
ci:test:saml:nocompile

**Comment by kenjiheigel** [comment]
ci:test:smoke:nocompile

**Comment by gaborlovasdotcom** [comment]
Nice, now it executed only once 👍

**Pull request closed without merging**
