### PR TITLE
LPS-141109 PoshiSourceProcessor

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Kenji,
I added logic to get macro and function list in `PoshiSourceProcessor`.

I also added a commit to use `poshi-runner` in `build.gradle` because `poshi-core` use `PoshiGetterUtil.getUtilityClassName` to get something to check class name, 
for example:
`var key_currentDateDay = DateUtil.getFormattedDate("0", "dd");`

`DateUtil` is from `poshi-runner`.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
Retesting here: 
https://github.com/kenjiheigel/liferay-portal/pull/923

**Pull request closed without merging**
