### PR TITLE
LRCI-2150

### PR DESCRIPTION
**Pull request by kenjiheigel**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:help

**Comment by kenjiheigel** [comment]
ci:help

**Comment by kenjiheigel** [comment]
ci:test:default:nocompile

**Comment by kenjiheigel** [comment]
ci:test:acceptance-functional:nocompile

**Comment by kenjiheigel** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
Hi @kenjiheigel, I found the a work solution to resolve the plus icon issue
I still need to make small change for locator
See https://github.com/kenjiheigel/liferay-portal/pull/778

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
