### PR TITLE
LPD-36494

### PR DESCRIPTION
**Pull request by kenjiheigel**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:playwright

**Comment by thiago-buarqque** [comment]
running it again because report was not generated

**Comment by thiago-buarqque** [comment]
ci:test:playwright

**Comment by thiago-buarqque** [comment]
ci:report:55636281

**Comment by thiago-buarqque** [comment]
Thanks Kenji

**Comment by thiago-buarqque** [comment]
ci:close

**Pull request closed without merging**
