### PR TITLE
LRCI-2776 Update the Testray README documentation for poshi-standalone

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-2776

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
Resent with additional updates here: 
https://github.com/kenjiheigel/liferay-portal/pull/967

**Pull request closed without merging**
