### PR TITLE
POSHI-79 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/POSHI-79

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
Pushed to Peter.
https://github.com/pyoo47/liferay-portal/pull/1326

@Tim-Cao, see my changes.

**Comment by Tim-Cao** [comment]
@kenjiheigel  Look better, thanks

**Pull request closed without merging**
