### PR TITLE
LPS-106232

### PR DESCRIPTION
**Pull request by kenjiheigel**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:jsf:nocompile

**Comment by ngriffin7a** [comment]
@kenjiheigel The following error indicates that the `-P liferay,liferay73` Maven profile was not specified on the command line when the WAR artifacts were built with `mvn clean install`:
```
     [exec] 17:05:27,073 ERROR [BridgeExtDependencyVerifier:45] Liferay Faces Bridge Ext 5.0.5 (Dec 20, 2019 AD) is designed to be used with Liferay Portal 7.0.x/7.1.x/7.2.x but detected 7.3
```

Also, the failures with ADFFaceletsApplicantPortletTester and ADFJSPApplicantPortletTester can be ignored. We're not supporting ADF yet. There are two ways to avoid running these tests:

1. Delete these files before running the tests:
- https://github.com/liferay/liferay-faces-bridge-impl/blob/4.1.4/test/integration/src/test/java/com/liferay/faces/bridge/test/integration/demo/applicant/ADFFaceletsApplicantPortletTester.java
- https://github.com/liferay/liferay-faces-bridge-impl/blob/4.1.4/test/integration/src/test/java/com/liferay/faces/bridge/test/integration/demo/applicant/ADFJSPApplicantPortletTester.java

2. Specify the `-Dit.test` command line argument when running the test: For example, this runs only the "Applicant" tests:
```
mvn verify -P selenium,liferay -Dit.test=\*Applicant\* -Dintegration.browser.headless=false
```

However, I'm not sure if there is a type of wildcard that can *exclude* the ADF tests. I would have to research that. For that reason, I recommend the first approach, which is to simply delete the .java source files before running the tests.

**Comment by kenjiheigel** [comment]
ci:test:jsf:nocompile

**Comment by kenjiheigel** [comment]
ci:test:jsf:nocompile

**Comment by kenjiheigel** [comment]
ci:test:jsf

**Comment by kenjiheigel** [comment]
ci:test:jsf:nocompile

**Comment by kenjiheigel** [comment]
ci:test:jsf:nocompile

**Comment by kenjiheigel** [comment]
ci:test:jsf:nocompile

**Comment by kenjiheigel** [comment]
ci:test:jsf:nocompile

**Comment by kenjiheigel** [comment]
ci:test:jsf:nocompile

**Pull request closed without merging**
