### PR TITLE
LPS-144442 Fix incorrect syntax, don't use nested CDATA

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
@kenjiheigel I did some research online,  and found xml doesn't allow nested CDATA.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
ci:forward

**Pull request closed without merging**
