### PR TITLE
LPS-65002 Updates task cache

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@brunobasto, there's some weird failures that I'm trying to figure out right now. I thought they were flaky tests at first, but it seems to do with the way we order the tests. I'll need more time to figure out the root issues, so I might not be able to get this sent to BChan today :(

**Comment by kenjiheigel** [comment]
@brunobasto, just an update with the failures for this.. In the test, it seems that it's adding two pages, then it tries to add two Documents. It only happens on a portal instance while running the test. I can't reproduce it manually, but can reproduce it after running the test. One of the weirder issues I've seen. Any ideas how this might have caused that?

**Comment by brunobasto** [comment]
Hey Kenji,

I might have an idea. Thanks for finding this. I'll resend.

**Comment by kenjiheigel** [comment]
Thanks @brunobasto !

**Comment by kenjiheigel** [comment]
@brunobasto, quick question.. Do you think it could be possible this happens elsewhere in portal sporadically? I've noticed some tests that add virtual instances, users, sites fail because it ends up giving the error that the asset already exists. I'm pretty sure it's not cause of leftover data from previous tests, but could it be that a request is being sent twice? Doesn't fail in our tests often though.

**Comment by brunobasto** [comment]
Hey Kenji, I'm pretty sure this failure was due to my fix on this PR and is
not related to other failures that sometimes happen.

**Comment by kenjiheigel** [comment]
Thanks Bruno. Going to close this pull, since you're going to resend.

**Comment by kenjiheigel** [comment]
Resent in https://github.com/kenjiheigel/liferay-portal/pull/220

**Pull request closed without merging**
