### PR TITLE
POSHI-253 POSHI-303 POSHI-305

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-253
https://issues.liferay.com/browse/POSHI-303
https://issues.liferay.com/browse/POSHI-305

@ling-alan-huang, the CDATA parsing issue that you mentioned to me is fixed by POSHI-253. 

cc: @CalumR23, @Tim-Cao

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by ling-alan-huang** [comment]
Thanks @CalumR23 @kenjiheigel

**Comment by kenjiheigel** [comment]
ci:forward

**Pull request closed without merging**
