### PR TITLE
POSHI-211 Fix poshi script parsing to generate Poshi files

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-211

@ling-alan-huang

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
@kenjiheigel I will make some small changes and send to you later today.
Also I will take care of this SF errors.

**Comment by ling-alan-huang** [comment]
Added an additional commit and resent: https://github.com/kenjiheigel/liferay-portal/pull/901

**Comment by ling-alan-huang** [comment]
ci:close

**Pull request closed without merging**
