### PR TITLE
LRCI-2150 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRCI-2150

This is only for master.

@kenjiheigel

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
Good enough for the moment!

**Comment by kenjiheigel** [comment]
ci:test:upstream-functional:nocompile

**Comment by Tim-Cao** [comment]
Rebased!

**Comment by Tim-Cao** [comment]
ci:test:upstream-functional:nocompile

**Comment by kenjiheigel** [comment]
Comparison of results with upstream.  
https://testray.liferay.com/home/-/testray/runs/compare?formDate=1619544742331&testrayRunIdA=1528838025&testrayRunIdB=1528805333

There were a good amount of builds that failed due to build aborts or other reasons. Results are inconclusive right now. I'll try running this again next week when the load has died down, or with just the tests that failed.

**Comment by Tim-Cao** [comment]
ci:test:upstream-functional:nocompile

**Comment by kenjiheigel** [comment]
@Tim-Cao, I think this is within a good threshold:
https://testray.liferay.com/home/-/testray/runs/compare?formDate=1620240771953&testrayRunIdA=1530416354&testrayRunIdB=1530501713

I'm going to send this somewhere.

**Comment by kenjiheigel** [comment]
Pushed to liferay-qa: 
https://github.com/liferay-qa/liferay-portal/pull/403

**Pull request closed without merging**
